export const API = {
  SIGNUP: '/api/v1/users/signup',
  LOGIN: '/api/v1/users/login',
  USER_AVAILABLE: '/api/v1/users/available',
  LOGOUT: '/api/v1/users/logout',
  FORGOT_PASSWORD: '/api/v1/users/forgotPassword',
  RESET_PASSWORD: '/api/v1/users/resetPassword',
  INVITES: '/api/v1/invites',
  GROUPS: '/api/v1/groups',
  FRIENDS: '/api/v1/friends',
  GAMES: '/api/v1/games',
  GAME_HISTORY: '/api/v1/games/gameHistory',
  GAME_STATS: '/api/v1/games/gameStats',
  PLAYERS: '/api/v1/games/topPlayers',
  TOP_FRIENDS: '/api/v1/friends/topFriends',
  FRIENDSHIP_STATUS: '/api/v1/users/friendshipStatus',
  USERS: '/api/v1/users',
  FILES: '/api/v1/files',
  NOTIFICATIONS: '/api/v1/notifications',
  MUTUAL_FRIENDS: '/api/v1/friends/mutualFriends',
  USER_SEARCH: '/api/v1/users/search',
}
